#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           6 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


~/.config/polybar/launch.sh
feh --bg-scale ~/Pictures/nordic-wallpapers/wallpapers/ign_unsplash7.png
picom & 

# ~/.local/bin/eww open clock --toggle && ~/.local/bin/eww open monitor --toggle && ~/.local/bin/eww open user --toggle && ~/.local/bin/eww open bright --toggle && ~/.local/bin/eww open battery --toggle && ~/.local/bin/eww open memory --toggle

